import Head from "next/head";
import Menu from "./Menu";

export default function Header() {
  return (
    <>
      <Head>
        <title>Quoridor game</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Menu />
    </>
  );
}
